initialize:
  - run: |
      npm install
maintenance:
  - run: |
      npm install
knowledge:
  - name: lint
    contents: |
      npx tsc --noEmit
  - name: test
    contents: |
      npm run build
  - name: startup
    contents: |
      npm run dev
